# Generated by Django 6.0.4 on 2026-04-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('zip', models.IntegerField()),
                ('del_time', models.CharField(choices=[('1H', '1 Hour'), ('21H', '21 Hours'), ('27H', '27 Hours')], max_length=3)),
            ],
        ),
    ]
