# Generated by Django 6.0.4 on 2026-05-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
