# Generated by Django 6.0.4 on 2026-05-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cart_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
