# Generated by Django 6.0.4 on 2026-05-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_delivery_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='cart_items',
        ),
    ]
